import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Ganesh Bahire - Portfolio</title>
        <meta
          name="description"
          content="Welcome to Ganesh Bahire's portfolio. Explore my projects, skills, and experience as a full-stack developer."
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
